export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'USERS_SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'USERS_SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'USERS_SIGNUP_FAILURE';

export const START_LOADING_REQUEST = 'START_LOADING_REQUEST'
export const STOP_LOADING_REQUEST = 'STOP_LOADING_REQUEST'


export const REDIRECT = 'REDIRECT';